#!/bin/sh
# Generated by ScalaSemantic MCP setup -- do not edit; re-run `scalasemantic-mcp setup`
# to regenerate, or `scalasemantic-mcp setup --no-guard` to stop installing it (then drop
# the PreToolUse entry from .claude/settings.json).
#
# Claude Code PreToolUse hook, two jobs:
#   READS  -- text-scraping tools on .scala sources are denied, so symbol questions go to
#             the ScalaSemantic MCP tools, which answer from compiler facts at a fraction
#             of the tokens and without missing renames/implicits/inferred uses.
#   EDITS  -- writing a .scala source is allowed but reminds the agent to edit the
#             annotated buffer instead, so it edits with the compiler's inferred types and
#             implicits in view. `setup --strict-edits` turns that reminder into a denial.
#
# Exit codes: 0 = allow (stdout is fed back to the agent as context), 2 = deny (stderr is).

set -u
strict_edits=0

root="${CLAUDE_PROJECT_DIR:-$PWD}"
payload=$(cat)

# --- no JSON reader: fail open ---------------------------------------------------------
if command -v jq >/dev/null 2>&1; then
  reader=jq
elif command -v python3 >/dev/null 2>&1; then
  reader=python3
else
  exit 0
fi

# tool name, then the tool_input fields that can name a Scala target, one per line.
if [ "$reader" = jq ]; then
  fields=$(printf '%s' "$payload" | jq -r '
    [ (.tool_name // ""),
      (.tool_input.file_path // ""),
      (.tool_input.glob // ""),
      (.tool_input.path // ""),
      (.tool_input.type // ""),
      (.tool_input.command // "") ]
    | .[] | tostring | gsub("\n"; " ")' 2>/dev/null) || exit 0
else
  fields=$(printf '%s' "$payload" | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
i = d.get("tool_input") or {}
keys = ["file_path", "glob", "path", "type", "command"]
out = [d.get("tool_name", "")] + [i.get(k, "") for k in keys]
print("\n".join(str(x).replace("\n", " ") for x in out))
' 2>/dev/null) || exit 0
fi

[ -n "$fields" ] || exit 0
tool=$(printf '%s\n' "$fields" | sed -n 1p)
file_path=$(printf '%s\n' "$fields" | sed -n 2p)
glob=$(printf '%s\n' "$fields" | sed -n 3p)
path=$(printf '%s\n' "$fields" | sed -n 4p)
ftype=$(printf '%s\n' "$fields" | sed -n 5p)
command_line=$(printf '%s\n' "$fields" | sed -n 6p)

# --- explicit human/agent override -----------------------------------------------------
# `rg foo *.scala   # semantic-fallback: <reason>` is always allowed, and logged so the
# override stays auditable instead of silent.
case "$command_line" in
  *semantic-fallback:*)
    printf '%s\t%s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$command_line" \
      >>"$root/.claude/semantic-fallback.log" 2>/dev/null
    exit 0
    ;;
esac

# --- does this call target Scala sources, and is it a read or a write? -----------------
# mode: "" = not our business, "read" = text-scraping a Scala source, "write" = editing one.
mode=
case "$tool" in
  Read)
    case "$file_path" in
      *.scala | *.sc) mode=read ;;
    esac
    ;;
  Grep | Glob)
    # Only when the call itself names Scala: an unscoped repo-wide search may legitimately
    # be after comments, config or non-Scala files.
    case "$glob$path$ftype" in
      *scala*) mode=read ;;
    esac
    ;;
  Edit | Write | MultiEdit | NotebookEdit)
    case "$file_path" in
      *.scala | *.sc) mode=write ;;
    esac
    ;;
  Bash)
    # `.scala` must end a path, not merely appear: `mill.scalalib`, `scalafmt` and
    # `.scala-build` are not Scala sources, and blocking them blocks the build itself.
    if printf '%s' "$command_line" | grep -Eq '\.(scala|sc)([^[:alnum:]_-]|$)'; then
      if printf '%s' "$command_line" | grep -Eq \
        '(^|[|;&(`]|[[:space:]])(grep|rg|ag|ack|cat|sed|awk|head|tail|less|more|nl)([[:space:]]|$)'
      then
        mode=read
      fi
      # Handing the file to a runner is executing it, not reading it -- and the pipeline
      # that filters its OUTPUT (`scala-cli foo.sc | grep ...`) is not a text search either.
      if printf '%s' "$command_line" | grep -Eq \
        '(^|[|;&(`/]|[[:space:]])(scala-cli|scala|scalac|amm|mill|sbt|java)([[:space:]]|$)'
      then
        mode=
      fi
      # A redirect or in-place edit whose TARGET is the Scala file is a write, not a read --
      # and it outranks a reader that appears on the same line (`cat > A.scala`).
      if printf '%s' "$command_line" | grep -Eq \
        '(>>?|tee)[[:space:]]*"?[^[:space:]"]*\.(scala|sc)([[:space:]"]|$)|sed[[:space:]]+-i[^|;&]*\.(scala|sc)([[:space:]]|$)'
      then
        mode=write
      fi
    fi
    ;;
esac
[ -n "$mode" ] || exit 0

# --- fail open when the semantic answer is not actually available ----------------------
# No MCP server wired into this project: nothing better to route the agent to.
for cfg in "$root/.mcp.json" "$root/.claude/settings.json" "$root/.claude/settings.local.json"; do
  [ -f "$cfg" ] && grep -q 'scala-semantic' "$cfg" 2>/dev/null && configured=1
done
[ "${configured:-0}" = 1 ] || exit 0

# No SemanticDB emitted yet (never compiled, or a non-Scala project): the MCP tools would
# return an empty index, so text search is the only thing that can work.
index=$(find "$root" \
  \( -name .git -o -name out -o -name target -o -name node_modules -o -name .scala-build \
     -o -name .worktrees -o -name website \) -prune -o \
  -name '*.semanticdb' -print 2>/dev/null | head -n 1)
[ -n "$index" ] || exit 0

# --- editing a Scala source ------------------------------------------------------------
# Not a denial by default: a three-line change through Edit is cheaper than a whole-file
# roundtrip. The reminder exists because the annotated buffer is what makes the edit
# compiler-aware, and nothing else in the session mentions it at the moment of the edit.
if [ "$mode" = write ]; then
  if [ "$strict_edits" = 1 ]; then
    cat >&2 <<'MSG'
BLOCKED by ScalaSemantic guard (--strict-edits): edit .scala sources through the MCP write
path, so the edit is made against the compiler's view of the file:
  1. annotated_source(uri, format="compilable", sentinel=true)
     -> the source with inferred types, implicit args and conversions inline as
        /*SEM:...:SEM*/ blocks (no line-number gutter), plus its sha256
  2. edit that buffer, leaving the SEM blocks wherever they are
  3. annotated_source(uri, write=<edited text>, baseHash=<that sha256>)
     -> every SEM block is stripped before the file is saved
Both arguments matter: sentinel=true makes the notes machine-strippable, format=compilable
drops the read-only gutter. Any other read is a view, not a buffer -- writing it back would
persist annotations into the source, and is refused.
Re-run `scalasemantic-mcp setup` without --strict-edits to make this a reminder instead.
MSG
    exit 2
  fi
  cat <<'MSG'
ScalaSemantic: editing a Scala source. For an annotation-aware edit, work on the annotated
buffer instead of the raw text:
  1. annotated_source(uri, format="compilable", sentinel=true)
     -> inferred types, implicit args and conversions inline as /*SEM:...:SEM*/ blocks
        (no line-number gutter), plus its sha256
  2. edit that buffer, leaving the SEM blocks in place
  3. annotated_source(uri, write=<edited text>, baseHash=<that sha256>)
     -> SEM blocks are stripped before the file is saved
Both arguments matter: sentinel=true makes the notes machine-strippable, format=compilable
drops the read-only gutter. Any other read is a view, not a buffer -- writing it back would
persist annotations into the source, and is refused.
A small mechanical edit can stay with this tool -- this is a reminder, not a refusal.
MSG
  exit 0
fi

# --- deny ------------------------------------------------------------------------------
cat >&2 <<'MSG'
BLOCKED by ScalaSemantic guard: text tools are not allowed on .scala sources here.
Text search misses renames, re-exports, implicits and inferred uses, and over-matches
comments and same-named identifiers. Use the mcp__scala-semantic__* tools instead and
pick whichever fits the actual question:
  symbols / references / types  -> find_symbol, find_usages, type_at_position
  hierarchy / members / givens  -> class_hierarchy, members, resolve_implicits
  signatures / overloads        -> method_signature, find_overloads
  file or project shape         -> document_outline, structure, symbol_source
  literals, comments, TODOs     -> search_text
Stale or missing index: run the project's compile task, then refresh_workspace — or, if you
cannot run the build yourself (e.g. this session cannot shell out), call refresh_workspace
with compile=true and it will detect and run the build itself.
If the semantic tools genuinely cannot answer this, re-run the command through Bash with
a trailing `# semantic-fallback: <reason>` marker (allowed, and logged).
MSG
exit 2
