#!/bin/sh
# Generated by ScalaSemantic MCP setup -- do not edit; re-run `scalasemantic-mcp setup`
# to regenerate, or `scalasemantic-mcp setup --no-guard` to stop installing it (then drop
# the PreToolUse entry from .claude/settings.json).
#
# Claude Code PreToolUse hook. Denies text-scraping tools on .scala sources so symbol
# questions go to the ScalaSemantic MCP tools, which answer from compiler facts at a
# fraction of the tokens and without missing renames/implicits/inferred uses.
#
# Exit codes: 0 = allow, 2 = deny (stderr is fed back to the agent).

set -u

root="${CLAUDE_PROJECT_DIR:-$PWD}"
payload=$(cat)

# --- no JSON reader: fail open ---------------------------------------------------------
if command -v jq >/dev/null 2>&1; then
  reader=jq
elif command -v python3 >/dev/null 2>&1; then
  reader=python3
else
  exit 0
fi

# tool name, then the tool_input fields that can name a Scala target, one per line.
if [ "$reader" = jq ]; then
  fields=$(printf '%s' "$payload" | jq -r '
    [ (.tool_name // ""),
      (.tool_input.file_path // ""),
      (.tool_input.glob // ""),
      (.tool_input.path // ""),
      (.tool_input.type // ""),
      (.tool_input.command // "") ]
    | .[] | tostring | gsub("\n"; " ")' 2>/dev/null) || exit 0
else
  fields=$(printf '%s' "$payload" | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
i = d.get("tool_input") or {}
keys = ["file_path", "glob", "path", "type", "command"]
out = [d.get("tool_name", "")] + [i.get(k, "") for k in keys]
print("\n".join(str(x).replace("\n", " ") for x in out))
' 2>/dev/null) || exit 0
fi

[ -n "$fields" ] || exit 0
tool=$(printf '%s\n' "$fields" | sed -n 1p)
file_path=$(printf '%s\n' "$fields" | sed -n 2p)
glob=$(printf '%s\n' "$fields" | sed -n 3p)
path=$(printf '%s\n' "$fields" | sed -n 4p)
ftype=$(printf '%s\n' "$fields" | sed -n 5p)
command_line=$(printf '%s\n' "$fields" | sed -n 6p)

# --- explicit human/agent override -----------------------------------------------------
# `rg foo *.scala   # semantic-fallback: <reason>` is always allowed, and logged so the
# override stays auditable instead of silent.
case "$command_line" in
  *semantic-fallback:*)
    printf '%s\t%s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$command_line" \
      >>"$root/.claude/semantic-fallback.log" 2>/dev/null
    exit 0
    ;;
esac

# --- does this call target Scala sources? ----------------------------------------------
targets_scala=0
case "$tool" in
  Grep | Glob)
    # Only when the call itself names Scala: an unscoped repo-wide search may legitimately
    # be after comments, config or non-Scala files.
    case "$glob$path$ftype" in
      *scala*) targets_scala=1 ;;
    esac
    ;;
  Bash)
    # Deny only when a text tool is INVOKED ON a Scala source. Three things this must not
    # confuse for that, all of which a whole-line substring test gets wrong:
    #   `com.example.scalasemantic.Foo`  -- a package name, not a path: the extension has to END
    #                                       a path-like token.
    #   `mill test | tail -5`            -- truncates output rather than reading source: the tool
    #                                       and the path must share a pipeline segment.
    #   `git add Foo.scala` (or any commit message mentioning grep) -- the tool name appears as an
    #                                       argument, not as the command: it must be the first
    #                                       word of its segment.
    _src_re='\.(scala|sc|mill)($|[^A-Za-z0-9_.-])'
    _tool_re='^[[:space:]]*(grep|rg|ag|ack|cat|sed|awk|head|tail|less|more|nl)([[:space:]]|$)'
    printf '%s\n' "$command_line" | sed 's/[|;]/\n/g; s/&&/\n/g' | while IFS= read -r seg; do
      printf '%s' "$seg" | grep -Eq "$_src_re" || continue
      printf '%s' "$seg" | grep -Eq "$_tool_re" || continue
      exit 1
    done || targets_scala=1
    ;;
esac
[ "$targets_scala" = 1 ] || exit 0

# --- fail open when the semantic answer is not actually available ----------------------
# No MCP server wired into this project: nothing better to route the agent to.
for cfg in "$root/.mcp.json" "$root/.claude/settings.json" "$root/.claude/settings.local.json"; do
  [ -f "$cfg" ] && grep -q 'scala-semantic' "$cfg" 2>/dev/null && configured=1
done
[ "${configured:-0}" = 1 ] || exit 0

# No SemanticDB emitted yet (never compiled, or a non-Scala project): the MCP tools would
# return an empty index, so text search is the only thing that can work.
index=$(find "$root" \
  \( -name .git -o -name out -o -name target -o -name node_modules -o -name .scala-build \
     -o -name .worktrees -o -name website \) -prune -o \
  -name '*.semanticdb' -print 2>/dev/null | head -n 1)
[ -n "$index" ] || exit 0

# --- deny ------------------------------------------------------------------------------
cat >&2 <<'MSG'
BLOCKED by ScalaSemantic guard: text SEARCH over Scala sources is not allowed here.
Text search misses renames, re-exports, implicits and inferred uses, and over-matches
comments and same-named identifiers. Use the mcp__scala-semantic__* tools instead and
pick whichever fits the actual question:
  symbols / references / types  -> find_symbol, find_usages, type_at_position
  hierarchy / members / givens  -> class_hierarchy, members, resolve_implicits
  signatures / overloads        -> method_signature, find_overloads
  file or project shape         -> document_outline, structure, symbol_source
  literals, comments, TODOs     -> search_text
Stale or missing index: run the project's compile task, then refresh_workspace.
If the semantic tools genuinely cannot answer this, re-run the command through Bash with
a trailing `# semantic-fallback: <reason>` marker (allowed, and logged).
MSG
exit 2
