rules = [
  OrganizeImports,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  RemoveUnused,
  RedundantSyntax
]

OrganizeImports {
  targetDialect = Scala3
  removeUnused = true
}

DisableSyntax {
  noAsInstanceOf = true
  noFinalVal = true
  noIsInstanceOf = true
  noNulls = true
  noReturns = true
  noThrows = true
  noVars = true
}
