package com.github.mercurievv.scalasemantic

import java.nio.file.FileVisitResult
import java.nio.file.FileVisitor
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.attribute.BasicFileAttributes
import java.util.concurrent.atomic.AtomicReference
import scala.jdk.CollectionConverters.*
import scala.util.Try

/** `scalasemantic-mcp doctor`: does this project actually get semantic answers, and would the guard
  * hook enforce anything?
  *
  * The guard is designed to fail open — no MCP server, no emitted SemanticDB, no JSON reader and it
  * lets the text tool through. That is the right default, but it is also silent: an install whose
  * index probe never matches looks exactly like a healthy one from the outside, and the failure
  * surfaces only much later as "the MCP tools somehow never got used". Every check here is one of
  * the conditions the hook script itself tests, run eagerly and reported in words.
  */
private[scalasemantic] object LauncherDoctor:

  final case class Check(ok: Boolean, label: String, detail: String):
    def line: String = s"${if ok then "ok  " else "FAIL"}  $label — $detail"

  final case class Report(checks: Vector[Check]):
    def installed: Boolean = checks.exists(c => c.label == GuardLabel && c.ok)

    /** The guard is installed and registered, yet one of its liveness conditions does not hold: it
      * will allow every text tool on every Scala source, and say nothing about it.
      */
    def failsOpen: Boolean = installed && checks.exists(c => LivenessLabels(c.label) && !c.ok)

    def lines: Vector[String] = checks.map(_.line)
    def failures: Vector[String] = checks.filterNot(_.ok).map(_.line)

  private val GuardLabel = "guard hook installed"
  private val ScriptLabel = "guard hook up to date"
  private val SettingsLabel = "guard hook registered"
  private val ServerLabel = "MCP server configured"
  private val IndexLabel = "SemanticDB index"
  private val ReaderLabel = "JSON reader for the hook"

  /** The conditions the hook checks before it is willing to deny anything. */
  private val LivenessLabels = Set(ScriptLabel, SettingsLabel, ServerLabel, IndexLabel, ReaderLabel)

  private val FailOpenAdvice =
    """|The guard fails open by design when it cannot offer a better answer, so text tools stay
       |allowed on .scala sources until every line above is ok. The usual fix is to compile the
       |project once (the build is what emits SemanticDB), or to re-run `scalasemantic-mcp setup`.""".stripMargin

  def run(args: List[String]): Unit =
    val project = parse(args)
    val report = inspect(project)
    LauncherMessages.err(s"doctor: $project")
    report.lines.foreach(l => Console.err.println(s"  $l"))
    if report.failsOpen then
      Console.err.println(FailOpenAdvice)
      sys.exit(1)

  /** The same report, printed at the end of `setup`: this class of breakage is cheapest to catch at
    * the moment the hook is written. Says nothing when the guard is live, and never exits non-zero
    * — setup itself succeeded.
    */
  def selfTest(project: Path): Unit =
    val report = inspect(project)
    if report.failsOpen then
      LauncherMessages.err("guard hook installed, but it will not block anything yet:")
      report.failures.foreach(l => Console.err.println(s"  $l"))
      Console.err.println(FailOpenAdvice)

  private def parse(args: List[String]): Path =
    args match
      case ("--project" | "--root") :: value :: _ => Path.of(value).toAbsolutePath.normalize()
      case ("--help" | "-h") :: _                 => LauncherMessages.usage(0)
      case bad :: _                               =>
        LauncherMessages.err(s"unknown doctor argument: $bad")
        LauncherMessages.usage(2)
      case Nil => Path.of(".").toAbsolutePath.normalize()

  def inspect(project: Path): Report =
    val hook = project.resolve(LauncherGuardHook.HookRelPath)
    val hookBody = if Files.exists(hook) then Some(Files.readString(hook)) else None
    val settings = project.resolve(".claude/settings.json")
    val settingsBody = if Files.exists(settings) then Files.readString(settings) else ""
    val registered = settingsBody.contains("scala-semantic-guard")
    val server = serverConfigured(project)
    val index = semanticdbIndex(project)
    val reader = jsonReader

    val checks = Vector(
      Check(
        hookBody.isDefined,
        GuardLabel,
        hookBody.fold(
          s"not installed: $hook (install it with `setup --rwhook-local`, or " +
            "`--rwhook-user` for every project; not having it is a valid choice)"
        )(_ => LauncherGuardHook.HookRelPath)
      ),
      Check(
        hookBody.forall(isCurrent),
        ScriptLabel,
        if hookBody.forall(isCurrent) then "matches this version of the launcher"
        else "generated by an older release — re-run `scalasemantic-mcp setup` to regenerate"
      ),
      Check(
        registered,
        SettingsLabel,
        if registered then s"PreToolUse entry in $settings"
        else s"no PreToolUse entry in $settings — the hook is never invoked"
      ),
      Check(
        server,
        ServerLabel,
        if server then "found in .mcp.json / .claude/settings*.json"
        else "no 'scala-semantic' entry in .mcp.json or .claude/settings*.json"
      ),
      Check(
        index.isDefined,
        IndexLabel,
        index.fold(
          "no *.semanticdb under any META-INF/semanticdb — compile the project " +
            "(Mill: `./mill __.compile`, sbt: `sbt compile`)"
        )(p => Try(project.relativize(p).toString).getOrElse(p.toString))
      ),
      Check(
        reader.isDefined,
        ReaderLabel,
        reader.getOrElse("neither jq nor python3 on PATH — the hook cannot read its payload")
      )
    )
    Report(checks)

  private def isCurrent(body: String): Boolean =
    body == LauncherGuardHook.script(strictEdits = false) ||
      body == LauncherGuardHook.script(strictEdits = true)

  private def serverConfigured(project: Path): Boolean =
    Vector(".mcp.json", ".claude/settings.json", ".claude/settings.local.json")
      .map(project.resolve)
      .exists(p =>
        Files.exists(p) && Try(Files.readString(p)).getOrElse("").contains("scala-semantic")
      )

  private def jsonReader: Option[String] =
    Vector("jq", "python3").find(cmd =>
      Try(
        scala.sys.process
          .Process(Seq("sh", "-c", s"command -v $cmd"))
          .!(scala.sys.process.ProcessLogger(_ => (), _ => ())) == 0
      ).getOrElse(false)
    )

  /** The hook's own index probe, in Scala: the first `*.semanticdb` anywhere under a
    * `META-INF/semanticdb` directory. Mill writes it to
    * `out/<mod>/semanticDbData.dest/classes/META-INF/semanticdb`, sbt somewhere under
    * `target/scala-3.x/.../META-INF/semanticdb` — i.e. inside the build's output directory, so
    * `out`/`target`/`.scala-build` must not be skipped here either. Only trees that can never hold
    * an index are pruned, exactly as the shell probe prunes them.
    */
  def semanticdbIndex(root: Path): Option[Path] =
    val pruned = Set(".git", "node_modules", ".worktrees", "website")
    val found = AtomicReference[Option[Path]](None)

    val visitor = new FileVisitor[Path]:
      def preVisitDirectory(dir: Path, attrs: BasicFileAttributes): FileVisitResult =
        if dir != root && pruned.contains(dir.getFileName.toString) then
          FileVisitResult.SKIP_SUBTREE
        else FileVisitResult.CONTINUE

      def visitFile(file: Path, attrs: BasicFileAttributes): FileVisitResult =
        if file.getFileName.toString.endsWith(".semanticdb") && underSemanticdbDir(file) then
          found.set(Some(file))
          FileVisitResult.TERMINATE
        else FileVisitResult.CONTINUE

      // An unreadable directory is not a reason to fail the probe: keep walking the rest.
      def visitFileFailed(file: Path, e: java.io.IOException): FileVisitResult =
        FileVisitResult.CONTINUE

      def postVisitDirectory(dir: Path, e: java.io.IOException | Null): FileVisitResult =
        FileVisitResult.CONTINUE

    val _ = Try(Files.walkFileTree(root, visitor))
    found.get()

  /** `META-INF/semanticdb` as two adjacent path segments — the file may sit any number of package
    * directories below it, which is why this is a segment scan and not a parent-name check.
    */
  private def underSemanticdbDir(file: Path): Boolean =
    val segments = file.iterator().asScala.map(_.toString).toVector
    segments.sliding(2).exists(pair => pair == Vector("META-INF", "semanticdb"))
