package com.github.mercurievv.scalasemantic.semanticdb

/** Phase 1: validate SemanticDB loading and symbol-grammar helpers by dogfooding on this build's
  * own emitted SemanticDB (regenerated by `compile`, which `test` depends on).
  */
class SemanticIndexSuite extends munit.FunSuite:

  // Loaded once; the analyzer's own class is guaranteed to be present in the index.
  private val idx = SemanticIndex.fromProject("target")

  private val Cls = "com/github/mercurievv/scalasemantic/semanticdb/SemanticIndex#"
  private val DisplayName =
    "com/github/mercurievv/scalasemantic/semanticdb/SemanticIndex#displayName()."
  private val Ctor = "com/github/mercurievv/scalasemantic/semanticdb/SemanticIndex#`<init>`()."

  test("loads documents and symbols from semanticdb artifacts") {
    assert(idx.documents.nonEmpty, "expected at least one TextDocument")
    assert(idx.symbols.contains(Cls), s"index should contain $Cls")
  }

  test("displayName decodes both indexed and escaped names") {
    assertEquals(idx.displayName(Cls), "SemanticIndex")
    assertEquals(idx.displayName(DisplayName), "displayName")
    // `<init>` is a backtick-escaped descriptor name — must round-trip cleanly.
    assertEquals(idx.displayName(Ctor), "<init>")
  }

  test("owner returns the enclosing scope, empty for nothing above package") {
    assertEquals(idx.owner(Cls), "com/github/mercurievv/scalasemantic/semanticdb/")
    assertEquals(idx.owner(DisplayName), Cls)
  }

  test("ownerChain runs outermost-first down to the symbol") {
    val chain = idx.ownerChain(DisplayName)
    assertEquals(chain.last, DisplayName)
    assert(chain.contains(Cls), s"chain should pass through $Cls: $chain")
    assert(
      chain.indexOf(Cls) < chain.indexOf(DisplayName),
      s"class must precede its method in $chain"
    )
  }

  test("kind predicates classify type vs method vs term") {
    assert(idx.isType(Cls), "class symbol should be a type")
    assert(!idx.isMethod(Cls), "class symbol is not a method")
    assert(idx.isMethod(DisplayName), "displayName() should be a method")
    assert(idx.isGlobal(Cls), "class symbol is global")
    assert(!idx.isLocal(Cls), "class symbol is not local")
  }
