// Docusaurus config for the ScalaSemantic microsite. The `docs/` content is GENERATED by mdoc
// (`sbt docs/run`), so snippet output is real. Build: `sbt docs/run` then, in website/,
// `npm install && npm run build` (or `npm start` to preview).
// @ts-check

const ORG = 'MercurieVV';
const REPO = 'ScalaSemantic';
const SITE = `https://mercurievv.github.io/${REPO}/`;
const DESCRIPTION =
  'MCP server for deep semantic analysis of Scala via SemanticDB — exact find-usages, class ' +
  'hierarchies, implicit/given resolution, and call paths for AI coding agents like Claude Code.';
const KEYWORDS = [
  'scala', 'scala 3', 'mcp', 'model context protocol', 'semanticdb', 'scalameta',
  'static analysis', 'semantic analysis', 'code intelligence', 'find usages', 'class hierarchy',
  'implicit resolution', 'call graph', 'claude code', 'ai coding agent', 'llm tools', 'sbt plugin',
];

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'ScalaSemantic',
  tagline: DESCRIPTION,
  url: 'https://mercurievv.github.io',
  baseUrl: `/${REPO}/`,
  organizationName: ORG,
  projectName: REPO,
  favicon: 'img/favicon.svg',
  trailingSlash: true, // stable URLs on GitHub Pages (served as directory indexes)

  // The docs are plain CommonMark (they contain `<root>`, `List[A]`, `{...}` that MDX would try to
  // parse as JSX/expressions). `detect` parses *.md as CommonMark and only *.mdx as MDX.
  markdown: { format: 'detect', hooks: { onBrokenMarkdownLinks: 'warn' } },

  // Docs link to repo files outside the site (../README.md, ../analysis/...) and to each other;
  // warn rather than fail the build on those.
  onBrokenLinks: 'warn',
  onBrokenAnchors: 'warn',

  // Structured data so search engines understand this is an open-source software project.
  headTags: [
    {
      tagName: 'script',
      attributes: { type: 'application/ld+json' },
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'SoftwareSourceCode',
        name: 'ScalaSemantic',
        description: DESCRIPTION,
        url: SITE,
        codeRepository: `https://github.com/${ORG}/${REPO}`,
        programmingLanguage: 'Scala',
        runtimePlatform: 'JVM',
        applicationCategory: 'DeveloperApplication',
        license: 'https://opensource.org/licenses/MIT',
        keywords: KEYWORDS.join(', '),
        author: { '@type': 'Person', name: 'Viktor Skalinins' },
      }),
    },
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: 'docs', // mdoc writes rendered Markdown here
          routeBasePath: '/',
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: `https://github.com/${ORG}/${REPO}/tree/master/docs/`,
        },
        blog: false,
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
          filename: 'sitemap.xml',
        },
        theme: {},
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Social card (og:image / twitter:image). Replace with a 1200×630 PNG for best rendering on
      // Twitter/Slack/LinkedIn; SVG is fine for Google.
      image: 'img/social-card.svg',
      metadata: [
        { name: 'keywords', content: KEYWORDS.join(', ') },
        { name: 'description', content: DESCRIPTION },
        { name: 'twitter:card', content: 'summary_large_image' },
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'ScalaSemantic' },
      ],
      navbar: {
        title: 'ScalaSemantic',
        logo: { alt: 'ScalaSemantic logo', src: 'img/logo.svg' },
        items: [
          { href: `https://github.com/${ORG}/${REPO}`, label: 'GitHub', position: 'right' },
        ],
      },
      footer: {
        style: 'dark',
        copyright: 'ScalaSemantic — MIT licensed.',
      },
    }),
};

module.exports = config;
