// Docusaurus config for the ScalaSemantic microsite. The `docs/` content is GENERATED by mdoc
// (`sbt docs/run`), so snippet output is real. Build the site with: `sbt docs/run` then, in website/,
// `npm install && npm run build` (or `npm start` to preview).
// @ts-check

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'ScalaSemantic',
  tagline: 'Deep semantic analysis of Scala projects over MCP',
  url: 'https://MercurieVV.github.io',
  baseUrl: '/ScalaSemantic/',
  organizationName: 'MercurieVV',
  projectName: 'ScalaSemantic',
  onBrokenLinks: 'warn',
  favicon: 'img/favicon.ico',

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          // mdoc writes rendered Markdown here.
          path: 'docs',
          routeBasePath: '/',
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: 'https://github.com/MercurieVV/ScalaSemantic/tree/master/docs/mdoc/',
        },
        blog: false,
        theme: {},
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: 'ScalaSemantic',
        items: [
          {
            href: 'https://github.com/MercurieVV/ScalaSemantic',
            label: 'GitHub',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'dark',
        copyright: 'MIT licensed.',
      },
    }),
};

module.exports = config;
