// The docs are generated by mdoc into website/docs. This sidebar mirrors the source tree so the
// public site has a clear reading path instead of exposing implementation/history pages first.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Get Started',
      link: {
        type: 'generated-index',
        title: 'Get Started',
        description: 'Install ScalaSemantic and answer setup questions.',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'getting-started/quickstart',
          label: 'Quickstart',
        },
        {
          type: 'doc',
          id: 'getting-started/integration',
          label: 'Integration',
        },
        {
          type: 'doc',
          id: 'getting-started/faq',
          label: 'FAQ',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        title: 'Reference',
        description: 'Tool surface and protocol details.',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'reference/tools',
          label: 'Tool Reference',
        },
      ],
    },
    {
      type: 'category',
      label: 'Use The Tools',
      link: {
        type: 'generated-index',
        title: 'Use The Tools',
        description: 'Concrete calls and representative responses.',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'usage/tool-examples',
          label: 'Tool Examples (Real Output)',
        },
      ],
    },
    {
      type: 'category',
      label: 'Explanation',
      link: {
        type: 'generated-index',
        title: 'Explanation',
        description: 'Trade-offs, limitations, and comparisons.',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'explanation/scala-semantic-vs-grep',
          label: 'ScalaSemantic vs grep',
        },
      ],
    },
    {
      type: 'category',
      label: 'Project',
      link: {
        type: 'generated-index',
        title: 'Project',
        description: 'Contributor, design, and release-maintenance docs.',
      },
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'project/development',
          label: 'Development',
        },
        {
          type: 'doc',
          id: 'project/design',
          label: 'Design Decisions',
        },
        {
          type: 'doc',
          id: 'project/releasing',
          label: 'Releasing',
        },
        {
          type: 'doc',
          // Docusaurus strips the "0001-" number prefix from the doc id.
          id: 'adr/claude-code-guard-hook',
          label: 'ADR 0001: Claude Code Guard Hook',
        },
        {
          type: 'doc',
          id: 'project/release-notes',
          label: 'Release Notes',
        },
      ],
    },
    {
      type: 'category',
      label: 'Research',
      link: {
        type: 'generated-index',
        title: 'Research',
        description: 'Planning notes and empirical agent-behavior studies.',
      },
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'research/claude-interaction-study',
          label: 'Claude Interaction Study',
        },
      ],
    },
    {
      type: 'category',
      label: 'Articles',
      link: {
        type: 'generated-index',
        title: 'Articles',
        description: 'Narrative writing and external-publication drafts.',
      },
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'articles/it-hurts-to-watch-ai-grep-my-scala',
          label: 'It Hurts to Watch an AI Grep My Scala',
        },
      ],
    },
  ],
};

module.exports = sidebars;
